name: quine-checker

ghc-options:
  - -Wall
  - -Wno-name-shadowing

dependencies:
  - base
  - shake
  - filepath
  - unix

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - silently
      - directory

