name: quine-checker

ghc-options:
  - -Wall
  - -Wno-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - base
      - hspec
      - mockery
